"""
Seed the reports table with realistic dummy community reports.
Run once: python scripts/seed_reports.py
"""
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import database as db

REPORTS = [
    # ── Dhaka Division ──────────────────────────────────────────────
    {
        "reporter_name": "Rahim Uddin",
        "title": "Truck overturns on Dhaka-Mymensingh highway near Gazipur",
        "description": "A loaded cement truck lost control and overturned near Joydebpur flyover early morning. Three labourers riding on top were thrown off. Traffic was blocked for over two hours.",
        "incident_date": "2026-02-27",
        "incident_time": "06:15",
        "location_text": "Joydebpur flyover, Dhaka-Mymensingh highway",
        "district": "Gazipur",
        "division": "Dhaka",
        "accident_type": "Truck accident",
        "fatalities": 1,
        "injuries": 3,
        "upvotes": 12,
    },
    {
        "reporter_name": "Sumaiya Begum",
        "title": "Bus-motorcycle collision in Savar leaves rider critical",
        "description": "A Dhaka-bound bus from Aricha ghat side-swiped a motorcycle near EPZ junction. The motorcyclist was rushed to Enam Medical College Hospital in critical condition.",
        "incident_date": "2026-02-26",
        "incident_time": "14:30",
        "location_text": "EPZ junction, Savar",
        "district": "Dhaka",
        "division": "Dhaka",
        "accident_type": "Motorcycle accident",
        "fatalities": 0,
        "injuries": 1,
        "upvotes": 8,
    },
    {
        "reporter_name": "Karim Hossain",
        "title": "Auto-rickshaw hit by speeding car on Mirpur Road",
        "description": "A CNG auto-rickshaw was T-boned by a private car running a red light at Kazipara intersection. Two passengers were injured, one with a fractured arm.",
        "incident_date": "2026-02-25",
        "incident_time": "09:45",
        "location_text": "Kazipara intersection, Mirpur Road",
        "district": "Dhaka",
        "division": "Dhaka",
        "accident_type": "Auto-rickshaw accident",
        "fatalities": 0,
        "injuries": 2,
        "upvotes": 5,
    },
    {
        "reporter_name": "Nasima Akter",
        "title": "Pedestrian killed by bus in Jatrabari",
        "description": "An elderly man crossing the road near Jatrabari flyover was struck by a BRTC bus. He died on the spot before ambulance arrived. Witnesses say the bus was overspeeding.",
        "incident_date": "2026-02-24",
        "incident_time": "07:00",
        "location_text": "Near Jatrabari flyover",
        "district": "Dhaka",
        "division": "Dhaka",
        "accident_type": "Pedestrian accident",
        "fatalities": 1,
        "injuries": 0,
        "upvotes": 21,
    },
    {
        "reporter_name": "Anonymous",
        "title": "Head-on collision on Tangail highway, 4 injured",
        "description": "Two minibuses collided head-on near Elenga bridge. Four passengers needed hospitalisation. Police say one driver fell asleep.",
        "incident_date": "2026-02-22",
        "incident_time": "03:30",
        "location_text": "Elenga bridge, Tangail highway",
        "district": "Tangail",
        "division": "Dhaka",
        "accident_type": "Bus accident",
        "fatalities": 0,
        "injuries": 4,
        "upvotes": 9,
    },

    # ── Chittagong Division ─────────────────────────────────────────
    {
        "reporter_name": "Farhan Sabbir",
        "title": "Multi-vehicle crash on Dhaka-Chittagong highway kills 3",
        "description": "A rear-end chain crash involving a bus, two trucks and a microbus near Meghna bridge took three lives. Foggy conditions and poor visibility were reportedly the main cause.",
        "incident_date": "2026-02-27",
        "incident_time": "05:00",
        "location_text": "Near Meghna bridge, Comilla side",
        "district": "Comilla",
        "division": "Chittagong",
        "accident_type": "Multi-vehicle collision",
        "fatalities": 3,
        "injuries": 7,
        "upvotes": 34,
    },
    {
        "reporter_name": "Lutfun Nahar",
        "title": "Motorbike accident on Cox's Bazar beach road",
        "description": "A tourist on a rental motorbike lost control on Marine Drive and hit a road divider. The rider sustained head injuries. Helmet was not being worn.",
        "incident_date": "2026-02-26",
        "incident_time": "16:20",
        "location_text": "Marine Drive, Cox's Bazar",
        "district": "Cox's Bazar",
        "division": "Chittagong",
        "accident_type": "Motorcycle accident",
        "fatalities": 0,
        "injuries": 1,
        "upvotes": 6,
    },
    {
        "reporter_name": "Imran Chowdhury",
        "title": "Truck hits school van in Feni, 6 children hurt",
        "description": "A school van carrying 12 students was side-swiped by an overtaking truck on Feni-Noakhali road. Six children sustained minor injuries. Parents are outraged demanding action.",
        "incident_date": "2026-02-23",
        "incident_time": "08:10",
        "location_text": "Feni-Noakhali road, Feni town",
        "district": "Feni",
        "division": "Chittagong",
        "accident_type": "Truck accident",
        "fatalities": 0,
        "injuries": 6,
        "upvotes": 47,
    },
    {
        "reporter_name": "Shirin Alam",
        "title": "Bus falls into canal in Brahmanbaria",
        "description": "A passenger bus veered off the narrow bridge near Ashuganj and dropped into the canal. Locals and fire service rescued 18 passengers. Two remain missing.",
        "incident_date": "2026-02-20",
        "incident_time": "22:45",
        "location_text": "Ashuganj canal bridge, Brahmanbaria",
        "district": "Brahmanbaria",
        "division": "Chittagong",
        "accident_type": "Bus accident",
        "fatalities": 2,
        "injuries": 8,
        "upvotes": 58,
    },

    # ── Rajshahi Division ───────────────────────────────────────────
    {
        "reporter_name": "Masud Rana",
        "title": "Rickshaw van crushed by truck near Rajshahi city bypass",
        "description": "A vegetable-laden rickshaw van was crushed under a reversing truck at Binodpur bazaar. Both van occupants died at the scene. The truck driver fled.",
        "incident_date": "2026-02-26",
        "incident_time": "11:30",
        "location_text": "Binodpur bazaar, Rajshahi bypass",
        "district": "Rajshahi",
        "division": "Rajshahi",
        "accident_type": "Truck accident",
        "fatalities": 2,
        "injuries": 0,
        "upvotes": 17,
    },
    {
        "reporter_name": "Rokeya Khatun",
        "title": "Road accident near Pabna sugar mill kills one",
        "description": "A motorcycle carrying two men collided with a bus near Pabna sugar mill gate. The pillion rider died instantly. The driver is in hospital with multiple fractures.",
        "incident_date": "2026-02-24",
        "incident_time": "19:00",
        "location_text": "Pabna sugar mill gate",
        "district": "Pabna",
        "division": "Rajshahi",
        "accident_type": "Motorcycle accident",
        "fatalities": 1,
        "injuries": 1,
        "upvotes": 10,
    },
    {
        "reporter_name": "Jakir Hossain",
        "title": "Train hits auto-rickshaw at unmanned level crossing in Natore",
        "description": "A CNG auto-rickshaw stalled on the tracks at an unmanned level crossing in Baraigram. The Dhaka-Rajshahi intercity train struck it. Two passengers died, one survived with critical injuries.",
        "incident_date": "2026-02-21",
        "incident_time": "13:15",
        "location_text": "Baraigram level crossing, Natore",
        "district": "Natore",
        "division": "Rajshahi",
        "accident_type": "Train accident",
        "fatalities": 2,
        "injuries": 1,
        "upvotes": 29,
    },

    # ── Khulna Division ─────────────────────────────────────────────
    {
        "reporter_name": "Dipankar Roy",
        "title": "Speeding pickup kills pedestrian near Khulna city college",
        "description": "A pedestrian crossing at a zebra crossing near Khulna city college was hit by a pickup truck that was speeding. Security cameras reportedly captured the incident.",
        "incident_date": "2026-02-27",
        "incident_time": "10:00",
        "location_text": "Near Khulna city college, Boyra",
        "district": "Khulna",
        "division": "Khulna",
        "accident_type": "Pedestrian accident",
        "fatalities": 1,
        "injuries": 0,
        "upvotes": 22,
    },
    {
        "reporter_name": "Ananya Das",
        "title": "Three motorcyclists injured in collision in Jessore",
        "description": "Two motorcycles collided head-on near Jessore bypass. All three riders fell on the road. One had a serious head wound. Bystanders provided first aid before the ambulance arrived.",
        "incident_date": "2026-02-25",
        "incident_time": "20:30",
        "location_text": "Jessore bypass road",
        "district": "Jessore",
        "division": "Khulna",
        "accident_type": "Motorcycle accident",
        "fatalities": 0,
        "injuries": 3,
        "upvotes": 7,
    },
    {
        "reporter_name": "Anonymous",
        "title": "Bus overturns on Mongla highway, 12 passengers hurt",
        "description": "A passenger bus carrying workers to the Mongla port area overturned after the driver lost control on a sharp bend. Twelve workers were hurt, four critically.",
        "incident_date": "2026-02-18",
        "incident_time": "06:50",
        "location_text": "Mongla highway, Bagerhat",
        "district": "Bagerhat",
        "division": "Khulna",
        "accident_type": "Bus accident",
        "fatalities": 0,
        "injuries": 12,
        "upvotes": 15,
    },

    # ── Sylhet Division ─────────────────────────────────────────────
    {
        "reporter_name": "Tanbir Ahmed",
        "title": "Car plunges into ditch on Sylhet-Sunamganj road",
        "description": "A private car carrying a family of five fell into a roadside ditch after a tyre burst on the hilly stretch near Salutikar. All five were injured; two children are in ICU.",
        "incident_date": "2026-02-26",
        "incident_time": "15:45",
        "location_text": "Salutikar, Sylhet-Sunamganj road",
        "district": "Sylhet",
        "division": "Sylhet",
        "accident_type": "Road accident",
        "fatalities": 0,
        "injuries": 5,
        "upvotes": 18,
    },
    {
        "reporter_name": "Nusrat Jahan",
        "title": "Truck-bus collision on Habiganj highway kills driver",
        "description": "A truck trying to overtake collided with an oncoming bus on the Habiganj-Nabiganj road. The truck driver was killed on the spot. Several bus passengers sustained minor cuts.",
        "incident_date": "2026-02-23",
        "incident_time": "08:30",
        "location_text": "Nabiganj road, Habiganj",
        "district": "Habiganj",
        "division": "Sylhet",
        "accident_type": "Multi-vehicle collision",
        "fatalities": 1,
        "injuries": 4,
        "upvotes": 11,
    },

    # ── Rangpur Division ────────────────────────────────────────────
    {
        "reporter_name": "Shafiqul Islam",
        "title": "5 killed as bus falls from Teesta bridge in Rangpur",
        "description": "A night coach lost brakes descending the Teesta bridge approach and broke through the railing, falling 20 feet. Five passengers died, eleven were rescued by locals and fire service.",
        "incident_date": "2026-02-19",
        "incident_time": "02:00",
        "location_text": "Teesta bridge, Rangpur",
        "district": "Rangpur",
        "division": "Rangpur",
        "accident_type": "Bus accident",
        "fatalities": 5,
        "injuries": 11,
        "upvotes": 72,
    },
    {
        "reporter_name": "Halima Khatun",
        "title": "Motorcycle crash in Dinajpur kills young man",
        "description": "A young man riding at high speed on new bypass road lost control and collided with a roadside tree. He was declared dead at Dinajpur Medical College Hospital.",
        "incident_date": "2026-02-25",
        "incident_time": "23:10",
        "location_text": "New bypass road, Dinajpur",
        "district": "Dinajpur",
        "division": "Rangpur",
        "accident_type": "Motorcycle accident",
        "fatalities": 1,
        "injuries": 0,
        "upvotes": 14,
    },
    {
        "reporter_name": "Rafiqul Hasan",
        "title": "Train derailment injures passengers in Lalmonirhat",
        "description": "A freight train derailed near Lalmonirhat junction after hitting a cow on the track, pulling two passenger carriages off the rails. Eleven passengers were hurt.",
        "incident_date": "2026-02-22",
        "incident_time": "17:30",
        "location_text": "Lalmonirhat rail junction",
        "district": "Lalmonirhat",
        "division": "Rangpur",
        "accident_type": "Train accident",
        "fatalities": 0,
        "injuries": 11,
        "upvotes": 26,
    },

    # ── Barisal Division ────────────────────────────────────────────
    {
        "reporter_name": "Sadia Islam",
        "title": "Auto-rickshaw flips into pond in Pirojpur",
        "description": "An overloaded auto-rickshaw carrying eight passengers flipped off a narrow village road and fell into a fishpond near Mathbaria. Three passengers drowned; five were rescued.",
        "incident_date": "2026-02-24",
        "incident_time": "17:00",
        "location_text": "Mathbaria, Pirojpur",
        "district": "Pirojpur",
        "division": "Barisal",
        "accident_type": "Auto-rickshaw accident",
        "fatalities": 3,
        "injuries": 5,
        "upvotes": 41,
    },
    {
        "reporter_name": "Ruhul Amin",
        "title": "Truck-motorcycle collision in Barisal city",
        "description": "A motorcyclist was killed at Rupatoli intersection when a truck making a U-turn failed to spot him. Evening rush hour made the rescue slow. CCTV footage has been requested.",
        "incident_date": "2026-02-26",
        "incident_time": "18:15",
        "location_text": "Rupatoli intersection, Barisal",
        "district": "Barishal",
        "division": "Barisal",
        "accident_type": "Truck accident",
        "fatalities": 1,
        "injuries": 0,
        "upvotes": 19,
    },

    # ── Mymensingh Division ─────────────────────────────────────────
    {
        "reporter_name": "Monir Hossain",
        "title": "School bus accident in Netrokona injures 9 students",
        "description": "A private school bus skidded off the road on a muddy surface after overnight rain near Durgapur. Nine students suffered bruises and cuts; no fatalities. Parents gathered at the hospital.",
        "incident_date": "2026-02-26",
        "incident_time": "07:45",
        "location_text": "Durgapur road, Netrokona",
        "district": "Netrokona",
        "division": "Mymensingh",
        "accident_type": "Bus accident",
        "fatalities": 0,
        "injuries": 9,
        "upvotes": 33,
    },
    {
        "reporter_name": "Tamanna Sultana",
        "title": "Rickshaw van hit by speeding microbus in Mymensingh",
        "description": "A vegetable vendor's rickshaw van was struck by a microbus near the Agricultural University gate. The vendor died from injuries. Students protested demanding speed bumps.",
        "incident_date": "2026-02-23",
        "incident_time": "12:00",
        "location_text": "Agricultural University gate, Mymensingh",
        "district": "Mymensingh",
        "division": "Mymensingh",
        "accident_type": "Pedestrian accident",
        "fatalities": 1,
        "injuries": 1,
        "upvotes": 38,
    },
    {
        "reporter_name": "Anonymous",
        "title": "Night bus crash in Jamalpur, 2 dead",
        "description": "A sleeper coach travelling from Dhaka to Jamalpur rammed into a stationary truck on the highway in the early hours. Two passengers in the front seats were killed on impact.",
        "incident_date": "2026-02-20",
        "incident_time": "01:30",
        "location_text": "Jamalpur highway near Islampur",
        "district": "Jamalpur",
        "division": "Mymensingh",
        "accident_type": "Multi-vehicle collision",
        "fatalities": 2,
        "injuries": 6,
        "upvotes": 24,
    },
]


def seed():
    db.init_db()
    with db.get_db() as conn:
        existing = conn.execute("SELECT COUNT(*) as c FROM reports").fetchone()["c"]
        if existing >= len(REPORTS):
            print(f"Already have {existing} reports — skipping seed.")
            return

    inserted = 0
    for r in REPORTS:
        db.insert_report(
            title=r["title"],
            description=r["description"],
            incident_date=r["incident_date"],
            incident_time=r.get("incident_time"),
            location_text=r.get("location_text", ""),
            district=r.get("district"),
            division=r.get("division"),
            accident_type=r.get("accident_type", "Road accident"),
            fatalities=r.get("fatalities", 0),
            injuries=r.get("injuries", 0),
            reporter_name=r.get("reporter_name", "Anonymous"),
            images=[],
        )
        # Set upvotes directly (insert_report defaults to 0)
        with db.get_db() as conn:
            conn.execute(
                "UPDATE reports SET upvotes = ? WHERE title = ?",
                (r.get("upvotes", 0), r["title"]),
            )
        inserted += 1

    print(f"✅ Inserted {inserted} dummy reports.")


if __name__ == "__main__":
    seed()
